---
new_page_extension: md
auto_deploy: false
admin_path: ".vuepress/public/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/blog
  label: Posts
  create: all
  match: "**/*"
- type: heading
  label: Pages
- type: document
  path: src/index.md
  label: Home
- type: document
  path: src/about/index.md
  label: About
- type: document
  path: src/portfolio/index.md
  label: Portfolio
- type: document
  path: src/blog/index.md
  label: Blog
upload_dir: ''
public_path: https://assets.mattmcadams.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
