<template>
<layout>
  <div class="container">
    <h1>Privacy</h1>
    <p>This website is designed, developed, and maintained by Matthew McAdams, and all of this website's <a href="https://github.com/MattMcAdams/website">source code can be found on GitHub</a>. If you have any concerns about privacy, copyright, website performance, or if you find an issue with the website, please contact me using the <a href="https://www.mattmcadams.com/#contact">contact form</a> on the front page of this site, <a href="https://github.com/MattMcAdams/Website/issues/new">submit an issue</a> to this website's repository, or reach out to me on <a href="https://twitter.com/mattmakesart">Twitter</a>. Please let me know if you've found any discrepancy with this document.</p>
    <h2>Technology</h2>
    <p>This website is hosted on <a href="https://www.netlify.com/">Netlify</a> and uses their DNS, Forms, and Large Media solutions. I use <a href="https://plausible.io/">Plausible</a> for website analytics and <a href="https://github.com/">GitHub</a> for source control. This is a static website generated by <a href="https://gridsome.org/">Gridsome</a>.</p>
    <h2>What I collect and why</h2>
    <p>I take privacy very seriously and make sure I'm not collecting any personal data without your express permission. Here's a breakdown of everything I collect, how I collect it, and what I use it for.</p>
    <h3>Analytics</h3>
    <p>I'm using Plausible Analytics, which is a GDPR, CCPA and cookie law compliant site analytics tool. Data collected includes websites that send me traffic, pages on my site that are visited, duration of the visits, information from the devices (device type, operating system, country and browser) used during the visit and little more. You can see full details in <a href="https://plausible.io/data-policy">Plausible's data policy</a>.</p>
    <h3>Local Storage</h3>
    <p>I make use of the browser's local storage to remember your theme preference when you return to the website. I don't use local storage or cookies for any kind of tracking or analytics.</p>
    <h3>Voluntary Correspondence</h3>
    <p>When you contact me through the website's contact form, I keep that correspondence, including the email address, so that I have a history of past correspondences to reference if you reach out in the future. I also keep any emails or messages sent to me directly.</p>
  </div>
</layout>
</template>

<script>
export default {
  metaInfo: {
    title: 'Privacy'
  }
}
</script>
